export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const SET_SEARCH_COUNTRY = 'SET_SEARCH_COUNTRY';
